<?php
$modversion['name'] = _MYQUIZ_NAME;
$modversion['version'] = "4.0";
$modversion['description'] = _MYQUIZ_DESC;
$modversion['credits'] = "";
$modversion['author'] = "Metemet (www.xoops-tr.com)";
$modversion['help'] = "";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "quiz_logo.gif";
$modversion['dirname'] = "myquiz";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][0]['name'] = _MYQUIZ_RESULTALL; 
$modversion['sub'][0]['url'] = "results.php"; 

// Blocks
$modversion['blocks'][1]['file'] = "myquiz_block.php";
$modversion['blocks'][1]['name'] = "Active Quizzes";
$modversion['blocks'][1]['description'] = 'List of active quizzes';
$modversion['blocks'][1]['show_func'] = "b_myquiz_show";
$modversion['blocks'][1]['template'] = "myquiz_block.html";
#
$modversion['blocks'][2]['file'] = "myquiz_scores.php";
$modversion['blocks'][2]['name'] = 'Scores';
$modversion['blocks'][2]['description'] = 'Block that shows scores';
$modversion['blocks'][2]['show_func'] = "b_scores_show";
$modversion['blocks'][2]['template'] = "myquiz_scores.html";
#
$modversion['blocks'][3]['file'] = "myquiz_random.php";
$modversion['blocks'][3]['name'] = 'Random Question';
$modversion['blocks'][3]['description'] = 'Shows a random question from database';
$modversion['blocks'][3]['show_func'] = "rand_show";
$modversion['blocks'][3]['template'] = "myquiz_random.html";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "myquiz_admin";
$modversion['tables'][1] = "myquiz_categories";
$modversion['tables'][2] = "myquiz_check";
$modversion['tables'][3] = "myquiz_data";
$modversion['tables'][4] = "myquiz_datacontrib";
$modversion['tables'][5] = "myquiz_desc";
$modversion['tables'][6] = "myquiz_descontrib";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'qidir';
$modversion['comments']['pageName'] = 'comment_s.php';


// Templates
$modversion['templates'][1]['file'] = "comments.html";
$modversion['templates'][1]['description'] = '';


?>